### ISSUE TITLE
Update minimum Java version to 11

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/consul-client#13]

**Comment by chabala** [comment]
Why move the minimum from 8? Is this still the case?

**Comment by chabala** [comment]
But, are you doing anything that would preclude using Java 8? I can't advocate to move to this instead of com.orbit.consul:consul-client if it doesn't run on JDK8.

The real question is do you think not supporting Java 8 is worth someone else maintaining another fork of com.orbit.consul:consul-client to support Java 8?
